edition = "2021"
unstable_features = true
brace_style = "SameLineWhere"
attr_fn_like_width = 70
control_brace_style = "AlwaysSameLine"
imports_indent = "Block"
indent_style = "Block"
max_width = 120
error_on_line_overflow = true
tab_spaces = 4
newline_style = "Unix"
reorder_imports = true
